name: 'Hello World'
description: 'Greet someone and record the time'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  region:
    description: 'Buddy region'
    required: true
  provider_id:
    description: 'Provider ID of ?'
    required: true
  audience:
    description: 'Audience of ?'
    required: false
    branding:
      icon: 'circle'
      color: 'blue'
outputs:
  output:
    description: 'Some output, not sure what yet'
