name: 'Buddy Login'
description: 'Authenticate with Buddy CI/CD platform using GitHub OIDC'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  region:
    description: 'Buddy region (EU or US). Cannot be used with api_url.'
    default: 'US'
    required: false
  api_url:
    description: 'Custom API URL for on-premise Buddy installations. Cannot be used with region.'
    required: false
  provider_id:
    description: 'UUID of your Buddy OIDC provider configuration'
    required: true
  audience:
    description: 'Audience for which the GitHub OIDC provider token is intended'
    required: false
outputs:
  token:
    description: 'Buddy Personal Access Token that can be used to authenticate API requests in subsequent workflow steps'
branding:
  icon: 'circle'
  color: 'blue'
