name: 'Buddy Login'
description: 'Authenticate with Buddy CI/CD platform'
author: 'Cyprian Zdebski'
runs:
  using: 'node24'
  main: 'dist/index.js'
inputs:
  provider_id:
    description: 'UUID of your Buddy OIDC provider configuration. Required for OIDC authentiaction. Recommendation: Store authentication tokens in GitHub Secrets to keep credentials secure and out of your codebase.'
    required: false
  token:
    description: 'The PAT (Personal Access Token). Required if not using OIDC authentication. Recommendation: Store authentication tokens in GitHub Secrets to keep credentials secure and out of your codebase.'
    required: false
  region:
    description: 'Buddy region (EU, AP, or US). Cannot be used with api_url.'
    default: 'US'
    required: false
  api_url:
    description: 'Custom API URL for on-premise Buddy installations. Cannot be used with region.'
    required: false
  audience:
    description: 'Audience for which the GitHub OIDC provider token is intended.'
    required: false
  debug:
    description: 'Enable debug logging for troubleshooting'
    required: false
outputs:
  token:
    description: 'Buddy token that can be used to authenticate API requests in subsequent workflow steps. It is also exported as BUDDY_TOKEN variable'
  api_endpoint:
    description: 'The URL to Buddy API endpoint. It is also exported as BUDDY_API_ENDPOINT variable.'
branding:
  icon: 'log-in'
  color: 'blue'
