on: [push, workflow_dispatch]

jobs:
  test_buddy_login:
    runs-on: ubuntu-latest
    name: Test Buddy Login Action
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Buddy
        id: buddy_login
        uses: ./
        with:
          api_url: 'https://api.awsstage.net'
          provider_id: '3ece95dc-0985-432f-9593-d89d8e4b7081'
          audience: 'buddy-tests'
      - name: Test BUDDY_TOKEN environment variable
        run: |
          if [ -z "$BUDDY_TOKEN" ]; then
            echo "Error: BUDDY_TOKEN is not set"
            exit 1
          else
            echo "Success: BUDDY_TOKEN is set"
            echo "Token starts with: ${BUDDY_TOKEN:0:10}..."
          fi
      - name: Show encoded token (for debugging)
        run: |
          ENCODED_VAR=$(echo "$BUDDY_TOKEN" | base64)
          echo "Encoded token: $ENCODED_VAR"
      - name: Test step output
        run: |
          if [ -z "${{ steps.buddy_login.outputs.token }}" ]; then
            echo "Error: Step output token is not set"
            exit 1
          else
            echo "Success: Step output token is set"
            echo "Token from output starts with: ${{ steps.buddy_login.outputs.token }}" | cut -c1-10
          fi
      - name: Call Buddy API to verify token
        run: |
          echo "Testing token with Buddy API..."
          curl -X GET "https://api.awsstage.net/user" \
            -H "Authorization: Bearer $BUDDY_TOKEN" \
            -H "Content-Type: application/json" \
            -v
