on: [ push ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: buddy/login test action
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Buddy login action step
        uses: ./
        id: buddy_login
        with:
          provider_id: 'c778e240-9750-4a8f-b04a-5be9045badd3'
          region: 'EU'
      - name: Get the output
        run: |
          echo "Fetched data is ${{ steps.buddy_login.outputs.data }}"
