on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: buddy/login test action
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Buddy login action step
        uses: ./
        with:
          provider_id: 'c778e240-9750-4a8f-b04a-5be9045badd3'
          region: 'EU'
      - name: Test BUDDY_TOKEN is set
        run: |
          if [ -z "$BUDDY_TOKEN" ]; then
            echo "Error: BUDDY_TOKEN is not set"
            exit 1
          else
            echo "Success: BUDDY_TOKEN is set"
            echo "Token starts with: ${BUDDY_TOKEN:0:10}..."
          fi
