on: [ push ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test the buddy/login action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Buddy login action step
        uses: ./
        id: buddy_login
        with:
          audience: 'idk'
          provider_id: 'c778e240-9750-4a8f-b04a-5be9045badd3'
          region: 'EU'
      - name: Print the inputs
        run: |
          echo "The region is ${{ inputs.region }}"
          echo "The provider_id is ${{ inputs.provider_id }}"
          echo "The audience is ${{ inputs.audience }}"
      - name: Get the output
        run: echo "The output was ${{ steps.buddy_login.outputs.output }}"
      - name: Print envs
        run: |
          echo "The token is ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}"
