name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      action_ref:
        required: true
        type: string
        description: 'Action reference (e.g., "./" or "buddy/login@v1")'
      test_name:
        required: true
        type: string
        description: 'Test name for display'

jobs:
  test_oidc:
    name: Test OIDC - ${{ inputs.test_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Buddy (OIDC)
        id: buddy_login
        uses: ${{ inputs.action_ref }}
        with:
          debug: true
          api_url: 'https://api.awsstage.net'
          provider_id: ${{ secrets.BUDDY_PROVIDER_ID }}
          audience: 'buddy'
      - name: Test BUDDY_TOKEN environment variable
        run: |
          if [ -z "$BUDDY_TOKEN" ]; then
            echo "Error: BUDDY_TOKEN is not set"
            exit 1
          else
            echo "Success: BUDDY_TOKEN is set"
          fi
      - name: Test BUDDY_API_ENDPOINT environment variable
        run: |
          if [ -z "$BUDDY_API_ENDPOINT" ]; then
            echo "Error: BUDDY_API_ENDPOINT is not set"
            exit 1
          else
            echo "Success: BUDDY_API_ENDPOINT is set ($BUDDY_API_ENDPOINT)"
          fi
      - name: Test step outputs
        run: |
          if [ -z "${{ steps.buddy_login.outputs.api_key }}" ]; then
            echo "Error: Step output api_key is not set"
            exit 1
          else
            echo "Success: Step output api_key is set"
          fi
          if [ -z "${{ steps.buddy_login.outputs.api_endpoint }}" ]; then
            echo "Error: Step output api_endpoint is not set"
            exit 1
          else
            echo "Success: Step output api_endpoint is set"
          fi
      - name: Call Buddy API to verify token
        run: |
          echo "Testing OIDC token with Buddy API..."
          curl -X GET "$BUDDY_API_ENDPOINT/user" \
            -H "Authorization: Bearer $BUDDY_TOKEN" \
            -H "Content-Type: application/json"

  test_pat:
    name: Test PAT - ${{ inputs.test_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Buddy (PAT)
        id: buddy_login
        uses: ${{ inputs.action_ref }}
        with:
          debug: true
          api_key: ${{ secrets.BUDDY_PAT }}
          api_url: 'https://api.awsstage.net'
      - name: Test BUDDY_TOKEN environment variable
        run: |
          if [ -z "$BUDDY_TOKEN" ]; then
            echo "Error: BUDDY_TOKEN is not set"
            exit 1
          else
            echo "Success: BUDDY_TOKEN is set"
          fi
      - name: Test BUDDY_API_ENDPOINT environment variable
        run: |
          if [ -z "$BUDDY_API_ENDPOINT" ]; then
            echo "Error: BUDDY_API_ENDPOINT is not set"
            exit 1
          else
            echo "Success: BUDDY_API_ENDPOINT is set ($BUDDY_API_ENDPOINT)"
          fi
      - name: Test step outputs
        run: |
          if [ -z "${{ steps.buddy_login.outputs.api_key }}" ]; then
            echo "Error: Step output api_key is not set"
            exit 1
          else
            echo "Success: Step output api_key is set"
          fi
          if [ -z "${{ steps.buddy_login.outputs.api_endpoint }}" ]; then
            echo "Error: Step output api_endpoint is not set"
            exit 1
          else
            echo "Success: Step output api_endpoint is set"
          fi
      - name: Call Buddy API to verify token
        run: |
          echo "Testing PAT with Buddy API..."
          curl -X GET "$BUDDY_API_ENDPOINT/user" \
            -H "Authorization: Bearer $BUDDY_TOKEN" \
            -H "Content-Type: application/json"
